core:
  environment: "dev"
  lable: "{{cookiecutter.app_name}}"
api:
  port: ":8088"
  health_port: ":1499"
  metric_uri: "/metrics"
  health_uri: "/healthz"
log:
  level: "info"
  api_level: "warning"
{% if cookiecutter.use_postgresql == "y" %}
storage:
  host: "localhost"
  username: "go"
  password: "go"
  database: "{{cookiecutter.app_name}}"
  port: 5432
{% endif %}
{% if cookiecutter.use_redis == "y" %}
  redis_host: "localhost"
  redis_db: 0
  redis_port: 6379
  redis_password: ""
{% endif %}